export const URL_BASE: string = 'http://qa.calymayor.com.mx/CEF-WEB/public'
	// export const URL_BASE: string = 'http://44c2f988.ngrok.io'
export const TOKEN: string = '1VCLSYZJDRk68oHdTWZM5FcHYPBiz5DlBo5ywcVz'
export const CLIENT_ID: string = '2'
export const HEADER: string = 'application/json'