// export const URL_BASE: string = 'http://qa.calymayor.com.mx/CEF-WEB/public'
export const URL_BASE: string = 'http://b45ff851.ngrok.io'
export const TOKEN: string = 'uU5ol4miLzbUG5E0ZclbgRNza4aqfBT2c8jMlqeO'
export const CLIENT_ID: string = '2'
export const HEADER: string = 'application/json'